version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reactpress
      MYSQL_USER: reactpress
      MYSQL_PASSWORD: reactpress
    volumes:
      - db_data:/var/lib/mysql

  server:
    image: fecommunity/reactpress-server:latest
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=reactpress
      - DB_PASSWD=reactpress
      - DB_DATABASE=reactpress

  client:
    image: fecommunity/reactpress-client:latest
    restart: always
    depends_on:
      - server

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - client
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data: