services:
  db:
    image: mysql:5.7
    container_name: reactpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-reactpress}
      MYSQL_USER: ${DB_USER:-reactpress}
      MYSQL_PASSWORD: ${DB_PASSWD:-reactpress}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - reactpress-network

  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    container_name: reactpress_server
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-reactpress}
      - DB_PASSWD=${DB_PASSWD:-reactpress}
      - DB_DATABASE=${DB_DATABASE:-reactpress}
    networks:
      - reactpress-network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    container_name: reactpress_client
    restart: always
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    networks:
      - reactpress-network

  nginx:
    image: nginx:alpine
    container_name: reactpress_nginx
    ports:
      - "8080:80"
    depends_on:
      - client
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - reactpress-network

volumes:
  db_data:

networks:
  reactpress-network:
    driver: bridge