# This workflow will run tests and publish packages to npm when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      publish_type:
        description: 'Publish type'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - patch
          - minor
          - major

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm test
        if: false  # Skip tests for now as there are no test scripts defined

  publish-npm:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm run build
      - name: Publish packages
        run: |
          # Set npm token for authentication
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          
          # Determine publish type
          if [ "${{ github.event_name }}" = "release" ]; then
            # For releases, publish as latest
            pnpm run release
          elif [ "${{ github.event.inputs.publish_type }}" = "beta" ]; then
            # For workflow dispatch with beta, publish as beta
            pnpm run release --tag beta
          else
            # For workflow dispatch with other types, increment version and publish
            pnpm run release --increment ${{ github.event.inputs.publish_type }}
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}